name: Bump version & Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
      prereleaseid:
        description: 'Prerelease id (rc)'
        required: false
        default: ''
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.DEPLOY_KEY}}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install npm packages
        run: npm ci
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Publish
        if: ${{ !github.event.inputs.prereleaseid }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}  
          NPM_CONFIG_PROVENANCE=true lerna publish ${{ github.event.inputs.version }} --y
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        if: ${{ github.event.inputs.prereleaseid }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          lerna publish ${{ github.event.inputs.version }} --preid ${{ github.event.inputs.prereleaseid }} --y
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push latest version
        run: git push origin main --follow-tags
