# NOTE: taken from https://github.com/MylesBorins/node-osc/blob/main/.github/workflows/bump-version.yml

name: Bump version & Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch / prerelease)"
        required: true
      prereleaseid:
        description: "Prerelease id (rc)"
        default: ""
      config:
        description: "The config for which to create a new version (css / scss / css-in-js)"
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install npm packages
        run: npm ci

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
        ## am I crazy or is this 'run' crazy?
      - name: bump version
        run: |
          npm version ${{ github.event.inputs.version }} -w configs/${{ github.event.inputs.config }} --no-git-tag-version --preid ${{ github.event.inputs.prereleaseid }}
          git add .
          git commit -m "configs-${{ github.event.inputs.config }} v$(npm pkg get version --prefix configs/${{ github.event.inputs.config }} | tr -d '"')"
          git tag @mediamonks/stylelint-config-${{ github.event.inputs.config }}@$(npm pkg get version --prefix configs/${{ github.event.inputs.config }} | tr -d '"') -m "configs-${{ github.event.inputs.config }} v$(npm pkg get version --prefix configs/${{ github.event.inputs.config }} | tr -d '"')"
      - name: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish -w configs/${{ github.event.inputs.config }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push latest version
        run: git push origin main --follow-tags
